# Generated by Django 4.2.3 on 2023-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_default_to_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='file',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(default='', upload_to='csv_files/'),
        ),
    ]
